[package]
name = "schema_guard_tokio"
version = "1.10.2"
authors = ["V.Krinitsyn <V.Krinitsyn@gmail.com>"]
edition = "2018"
description = "Schema Guard: YAML based Relation Database Schema Management tool"
homepage = "https://github.com/vkrinitsyn/schema_guard"
readme = "README.md"
documentation = "https://www.dbinvent.com/rdbm/guide/getting-started#declarative"
repository = "https://github.com/vkrinitsyn/schema_guard"
license = "MIT"

[lib]
name = "schema_guard_tokio"
path = "src/lib.rs"

[dependencies]

slog = { version = "^2.7", features=["max_level_debug"] }
lazy_static = "^1.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
yaml-rust = "^0.4"
yaml-validator = "0.2.0"
tokio = { version = "^1.36", features = ["test-util", "full"]}
tokio-postgres = { version = "^0.7"}

[features]
#default = ["slog"]
# show extra messages when do SQL execution using slog logger
slog = []
